module Sample2.Decode exposing (..)

{-| Generated by <https://github.com/pravdomil/Elm-JSON-Interop>.
-}

import Json.Decode as D exposing (Decoder)
import Sample2 as A
import Utils.Json.Decode_ as D_


sampleType2 : Decoder A.SampleType2
sampleType2 =
    D.lazy
        (\_ ->
            D.field "a" D.int
                |> D.andThen
                    (\a___ ->
                        case a___ of
                            0 ->
                                D.succeed A.SampleType2

                            _ ->
                                D.fail ("I can't decode \"SampleType2\", unknown variant with index " ++ String.fromInt a___ ++ ".")
                    )
        )
