module Sample2.Encode exposing (..)

{-| Generated by <https://github.com/pravdomil/Elm-JSON-Interop>.
-}

import Json.Encode as E
import Sample2 as A
import Utils.Json.Encode_ as E_ exposing (Encoder)


sampleType2 : Encoder A.SampleType2
sampleType2 =
    \v1 ->
        case v1 of
            A.SampleType2 ->
                E.object [ ( "_", E.int 0 ) ]
