module Sample2.Encode exposing (..)

{-| Generated by elm-json-interop.
-}

import Json.Encode as E
import Sample2 as A
import Utils.Json.Encode_ as E_


sampleType : A.SampleType -> E.Value
sampleType a =
    case a of
        A.SampleType ->
            E.object [ ( "_", E.int 0 ) ]
