module Sample2.Encode exposing (..)

{-| Generated by elm-json-interop.
-}

import Json.Encode as E
import Sample2 exposing (..)
import Utils.Json.Encode_ as E_ exposing (Encoder)


sampleType2 : Encoder SampleType2
sampleType2 =
    \v1 ->
        case v1 of
            SampleType2 ->
                E.object [ ( "_", E.int 0 ) ]
