module Id.Encode exposing (..)

{-| Generated by elm-json-interop.
-}

import Id as A
import Json.Encode as E
import Utils.Json.Encode_ as E_


id : A.Id -> E.Value
id a =
    case a of
        A.Id b ->
            E.object [ ( "_", E.int 0 ), ( "a", E.string b ) ]
